/*
 * This file is generated by jOOQ.
 */
package com.lph.create.product.repository.jooq;


import com.lph.create.product.repository.jooq.tables.TProductProduct;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index T_PRODUCT_PRODUCT_PRIMARY = Indexes0.T_PRODUCT_PRODUCT_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index T_PRODUCT_PRODUCT_PRIMARY = Internal.createIndex("PRIMARY", TProductProduct.T_PRODUCT_PRODUCT, new OrderField[] { TProductProduct.T_PRODUCT_PRODUCT.ID }, true);
    }
}
