/*
 * This file is generated by jOOQ.
 */
package com.lph.create.product.repository.jooq;


import com.lph.create.product.repository.jooq.tables.TProductProduct;
import com.lph.create.product.repository.jooq.tables.records.TProductProductRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TProductProductRecord> KEY_T_PRODUCT_PRODUCT_PRIMARY = UniqueKeys0.KEY_T_PRODUCT_PRODUCT_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<TProductProductRecord> KEY_T_PRODUCT_PRODUCT_PRIMARY = Internal.createUniqueKey(TProductProduct.T_PRODUCT_PRODUCT, "KEY_t_product_product_PRIMARY", TProductProduct.T_PRODUCT_PRODUCT.ID);
    }
}
