/*
 * This file is generated by jOOQ.
 */
package com.lph.create.product.repository.jooq;


import com.lph.create.product.repository.jooq.tables.TProductProduct;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>t_product_product</code>.
     */
    public static final TProductProduct T_PRODUCT_PRODUCT = com.lph.create.product.repository.jooq.tables.TProductProduct.T_PRODUCT_PRODUCT;
}
