server:
  port: 8881
spring:
  application:
    name: create-zuul
  cloud:
    config:
      name: lipenghui
      label: master
      profile: dev
zuul:
  routes:
    api-member:
      path: /member/**
      serviceId: create-member
    api-feign:
      path: /feign/**
      serviceId: create-feign
    api-configClient:
      path: /config-client/**
      serviceId: config-client