server:
  port: 8761


eureka:
  server:
        enableSelfPreservation: false #关闭自我保护机制
        evictionIntervalTimerInMs: 5000 #清理间隔（单位毫秒，默认是60*1000）
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eurka-server